### ISSUE TITLE
MiniLM-L12

### ISSUE THREAD

**Issue by kuan62** [ksanman/AllMiniLML6v2Sharp#5]
Hi, May I know MiniLM-L12 can work with this?

**Comment by teklot** [comment]
> Hi, May I know MiniLM-L12 can work with this?

I would like to know this as well. Thanks!

**Comment by ksanman** [comment]
I haven't tested it. Seeing as it has the same inputs and outputs as minil6, as long as it uses the same tokenizer I would think it would work.

**Comment by teklot** [comment]
Exported the "all-MiniLM-L12-v2" and loaded it along with its vocab via the AllMiniLmL6V2Embedder and then ran a test with a bunch of sentences. It works great, thanks!
