### ISSUE TITLE
Embedding values from GenerateEmbeddings does not match GenerateEmbedding is the input sentence is not the first in the requested set.

### ISSUE THREAD

**Issue by mwwhited** [ksanman/AllMiniLML6v2Sharp#6]
When using the `GenerateEmbeddings` operation I get the matched embedding if the input value is first element in the set.  Otherwise the embedding is does not match the expected value.  I would have assume that the embedding from `GenerateEmbeddings` and `GenerateEmbedding` would match regardless of the order.

(The code behind "Vector" may be found here https://github.com/mwwhited-forks/SqlClrVector if you think that is causing the issue.)

```csharp
    [DataTestMethod]
    [DataRow("Hello World!")]
    public void OtherEmbeddingTest(string input)
    {
        var embedder = new AllMiniLmL6V2Embedder();
        var single = embedder.GenerateEmbedding(input);
        string[] inputs = ["not it", input, "Another", input];
        var multiple = embedder.GenerateEmbeddings(inputs).ToArray();

        var singleVector = new Vector(single.ToArray());
        var multipleVectors = multiple.Select(e => new Vector(e.ToArray()));

        this.TestContext.WriteLine($"Single  : {Vector.VectorMagnitude(singleVector)} \"{input}\"");

        foreach (var vector in multipleVectors.Select((v, i) => (v, i)))
        {
            this.TestContext.WriteLine($"Vector {vector.i}: {Vector.VectorMagnitude(vector.v)} ({Vector.VectorDistance("cosine", singleVector, vector.v)}) \"{inputs[vector.i]}\"");
        }    
```

```output
    TestContext Messages:
Single  : 1.0000000074550142 "Hello World!"
Vector 0: 0.999999803531721 (0.87621489408339) "not it"
Vector 1: 1.000000081631468 (0.07751869180118631) "Hello World!"
Vector 2: 1.0000000336981583 (0.8806857575786939) "Another"
Vector 3: 1.000000081631468 (0.07751869180118631) "Hello World!"
```

**Comment by mwwhited** [comment]
Here, I created a test under my fork showing the issue

https://github.com/mwwhited-forks/AllMiniLML6v2Sharp/blob/08f988e12186060e6482fc682a4e71b8c1ec0ded/AllMiniLmL6V2Sharp.Tests/AllMiniLmL6V2.Test.cs#L115

```
[Fact]
 public void MultipleDifferentTest_NotFineIfOther()
 {
     var model = new AllMiniLmL6V2Embedder();
     string sentence = "This is an example sentence";
     string[] sentences = [ "Some other", sentence];
     var embedding = model.GenerateEmbedding(sentence);
     var embeddings = model.GenerateEmbeddings(sentences);
     Assert.NotNull(embedding);
     Assert.NotEmpty(embedding);
     Assert.NotNull(embeddings);
     Assert.NotEmpty(embeddings);
     Assert.Equal(sentences.Length, embeddings.Count());

     // Make sure all embeddings are the same.

     var exp = new List<Exception>();

     foreach (var batchEmbedding in embeddings.Select((value, index) => (value, index)))
     {
         try
         {
             Assert.Equal(1, TensorPrimitives.CosineSimilarity(batchEmbedding.value.ToArray(), embedding.ToArray()));

             Assert.True(batchEmbedding.value.SequenceEqual(embedding),
                 "Single embedding does not match a batch embedding");
         }
         catch (Exception ex)
         {
             if (sentences[batchEmbedding.index] == sentence)
                 exp.Add(new Exception($"{batchEmbedding.index}", ex));
         }
     }

     if (exp.Count > 0)
         throw new AggregateException(exp);
 }
```

**Comment by mwwhited** [comment]
Another note, the performance is dramatically better if you reuse the RunOptions and InferenceSession between requests.  I was able to make the batch processing faster just by reusing those values.  The performance was so much faster I didn't even need to use your version that stacked all the tokens together (which i think is what was causing the defect above anyway.

This version just create a private method where the RunOptions and InferenceSession were passed in ...
https://github.com/mwwhited-forks/AllMiniLML6v2Sharp/blob/dev/MakeFasterV2/AllMiniLmL6V2Sharp/AllMiniLmL6V2Embedder.cs

This version just adds the runoptions and inferencesession to the class itsself then implements IDisposable to clean it up (needs improved to have proper finalization but it works.
https://github.com/mwwhited-forks/AllMiniLML6v2Sharp/blob/dev/MakeFasterV2/AllMiniLmL6V2Sharp/CachedAllMiniLmL6V2Embedder.cs

... I can clean these up and submit a PR if you are interested

**Comment by ksanman** [comment]
Are you using CPU or GPU when testing? My testing shows GenerateEmbeddings is slower on GPU when ran as a for each loop like in your fix. 

I don't believe the cause of the bug is in stacking sentences together. It is in the pooling and normalizing logic. C# is not as intuitive as Numpy. 

I'm pretty busy right now, so won't look at the bug until the weekend. If you just looking for faster performance on CPU, look at the GenerateEmbeddingsAsync method. It runs each sentence in parallel. Will probably be faster on CPU.

**Comment by mwwhited** [comment]
CPU. I want this to run in process of a web server without GPU support.

I'm guessing this bug has something to do with the long context/padding and truncation as looking at the vectors it starts zeroing out some of the later elements in later embeddings. 

I have this working faster and more accurate in my project so I'm not in a rush.  I just wanted to let you know what I found to help reduce anyone else's frustration later.  As another note, my change for the parallel requests prevented that onnxexception from being thrown in your long context test.

I highly appreciate you having a working sentence transformer in c#.

**Comment by ksanman** [comment]
The issue was the attention mask was not being applied properly in GenerateEmbeddings. Everything else is working correctly. I verified it is producing similar results to the python sentence transforms package (floating point error and some onnx differences) and released a new package with the bug fix. Thanks for reporting it.

OnnxException should be thrown in the long context test when _truncate is set to false and the token count exceeds 512. This is how the sentence transformers package works as well. BERT can only accept a max token length of 512.
